---
- name: Pull Docker image
  docker_image:
    name: "{{ docker_image }}"
    source: pull

- name: Stop existing container
  docker_container:
    name: cicd-assignment
    state: stopped
  ignore_errors: yes

- name: Run Docker container
  docker_container:
    name: cicd-assignment
    image: "{{ docker_image }}"
    state: started
    restart_policy: always
    ports:
      - "8080:8080"